# Generated by Django 3.1.3 on 2020-11-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_remove_auction_list_auction_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_list',
            name='auction_description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
